### ISSUE TITLE
error TS2339: Property 'render' does not exist on type 'IRouterContext'.

### ISSUE THREAD

**Issue by linzp007** [Cacivy/koa-typescript#1]
我下代码下来试运行,vscode下编译报错, 是啥情况?
src/controller/index.ts(53,12): error TS2339: Property 'render' does not exist on type 'IRouterContext'.
src/controller/user/index.ts(7,10): error TS2339: Property 'session' does not exist on type 'IRouterContext'.
src/controller/user/index.ts(7,32): error TS2339: Property 'session' does not exist on type 'IRouterContext'.
src/controller/user/index.ts(11,38): error TS2339: Property 'session' does not exist on type 'IRouterContext'.
src/controller/user/login.ts(19,7): error TS2339: Property 'session' does not exist on type 'IRouterContext'.
src/controller/user/logout.ts(7,6): error TS2339: Property 'session' does not exist on type 'IRouterContext'.

nodejs 7.9

**Comment by Cacivy** [comment]
我在7.9版本下测试是可以的，可能是ts版本的问题
typings/koa-session.d.ts里自定义了session和render属性，应该是没有识别到
